require "nvchad.mappings"

-- add yours here

local map = vim.keymap.set

map("n", ";", ":", { desc = "CMD enter command mode" })
map("i", "jj", "<ESC>")
map("i", "оо", "<ESC>")
map('t', '<Esc>', '<C-\\><C-n>', { noremap = true })
map('t', '<jj>', '<C-\\><C-n>', { noremap = true })
map('t', '<оо>', '<C-\\><C-n>', { noremap = true })
map("n", "<leader>md", ":MarkdownPreview<CR>", { silent = true, desc = "Markdown Preview" })

-- Перемещение между окнами с помощью Ctrl + h/j/k/l
map("n", "<C-h>", "<C-w>h", { desc = "Перейти к окну слева" })
map("n", "<C-j>", "<C-w>j", { desc = "Перейти к окну снизу" })
map("n", "<C-k>", "<C-w>k", { desc = "Перейти к окну сверху" })
map("n", "<C-l>", "<C-w>l", { desc = "Перейти к окну справа" })

map("n", "<C-р>", "<C-w>h", { desc = "Перейти к окну слева" })
map("n", "<C-о>", "<C-w>j", { desc = "Перейти к окну снизу" })
map("n", "<C-л>", "<C-w>k", { desc = "Перейти к окну сверху" })
map("n", "<C-д>", "<C-w>l", { desc = "Перейти к окну справа" })

-- Опционально: можно добавить мапинги для изменения размеров окон
map("n", "<C-Up>", "<cmd>resize +2<cr>", { desc = "Увеличить высоту окна" })
map("n", "<C-Down>", "<cmd>resize -2<cr>", { desc = "Уменьшить высоту окна" })
map("n", "<C-Left>", "<cmd>vertical resize -2<cr>", { desc = "Уменьшить ширину окна" })
map("n", "<C-Right>", "<cmd>vertical resize +2<cr>", { desc = "Увеличить ширину окна" })

map("n", "<C-W>р", "<C-W>h")  -- влево (р → h)
map("n", "<C-W>о", "<C-W>j")  -- вниз (о → j)
map("n", "<C-W>л", "<C-W>k")  -- вверх (л → k)
map("n", "<C-W>д", "<C-W>l")  -- вправо (д → l)

map("n", "й", "q")
map("n", "ц", "w")
map("n", "у", "e")
map("n", "к", "r")
map("n", "е", "t")
map("n", "н", "y")
map("n", "г", "u")
map("n", "ш", "i")
map("n", "щ", "o")
map("n", "з", "p")
map("n", "ф", "a")
map("n", "ы", "s")
map("n", "в", "d")
map("n", "а", "f")
map("n", "п", "g")
map("n", "р", "h") 
map("n", "о", "j")
map("n", "л", "k")  
map("n", "д", "l")
map("n", "я", "z")
map("n", "ч", "x")
map("n", "с", "c")
map("n", "м", "v")
map("n", "и", "b")
map("n", "т", "n")
map("n", "ь", "m")

-- Дополнительные мапинги для визуального режима
map("v", "й", "q")
map("v", "ц", "w")
map("v", "у", "e")
map("v", "к", "r")
map("v", "е", "t")
map("v", "н", "y")
map("v", "г", "u")
map("v", "ш", "i")
map("v", "щ", "o")
map("v", "з", "p")
map("v", "ф", "a")
map("v", "ы", "s")
map("v", "в", "d")
map("v", "а", "f")
map("v", "п", "g")
map("v", "р", "h")
map("v", "о", "j")
map("v", "л", "k")
map("v", "д", "l")
map("v", "я", "z")
map("v", "ч", "x")
map("v", "с", "c")
map("v", "м", "v")
map("v", "и", "b")
map("v", "т", "n")
map("v", "ь", "m")

-- Мапинги для операторного режима (например, для d, y, c и т.д.)
map("o", "й", "q")
map("o", "ц", "w")
map("o", "у", "e")
map("o", "к", "r")
map("o", "е", "t")
map("o", "н", "y")
map("o", "г", "u")
map("o", "ш", "i")
map("o", "щ", "o")
map("o", "з", "p")
map("o", "ф", "a")
map("o", "ы", "s")
map("o", "в", "d")
map("o", "а", "f")
map("o", "п", "g")
map("o", "р", "h")
map("o", "о", "j")
map("o", "л", "k")
map("o", "д", "l")
map("o", "я", "z")
map("o", "ч", "x")
map("o", "с", "c")
map("o", "м", "v")
map("o", "и", "b")
map("o", "т", "n")
map("o", "ь", "m")

-- Специальные символы (может потребоваться дополнительная настройка)
map("n", "ж", ":")
map("n", "Ж", ":")
map("n", "б", ",")
map("n", "ю", ".")
map("n", ".", "/")
map("n", "э", "'")
map("n", "х", "[")
map("n", "ъ", "ъ")
map("n", "Ё", "~")
-- map({ "n", "i", "v" }, "<C-s>", "<cmd> w <cr>")
